audit_header: false
title: "California's Best Real Estate Training"
description: Kevin Peete, a top Real Estate Agent in California, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Kevin Peete
  title:
  license_number:
  about_markdown: |
    I'm a Real Estate Consultant serving Los Angeles Metro, Orange County and Inland Empire areas. I specialize in adding value to my clients lives. My business is built on happy clients. Happy clients drive me to become better at what I do, and give me a chance to earn more business and to continue to become a better real estate professionals.

    Real Estate is generally the largest asset that most of my clients own and control. As a real estate professional and advisors to my clients, my biggest asset to them is to add tremendous value to their lives by guiding my clients through what would otherwise be an extremely complex process. I understand that the transaction experience is not as “simple” buying a piece of jewelry or acquiring a piece of furniture. The process involves tremendous amount of communication and uncertainty, strategy and negotiation, education and paperwork, and most of all time and money… sometimes spread over 30-60-90 or more days. i take pride in guiding my clients through the emotional and transactional ups and downs and prepare my clients for a successful closing.
  market: California
  brand: RE/MAX PATRIOTS
  brokerage:
  address: 496 Magnolia Ave Ste 205 Riverside CA, 92503
  phone: 951-858-5942
  phone_type:
  phone2:
  phone2_type:
  email: kpsellshomes@sbcglobal.net
  url: http://joinremax.com/REMAX-PATRIOTS

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how RE/MAX PATRIOTS can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/WeAreREMAX
  linkedin_url: https://www.linkedin.com/in/kevinpeete/
  youtube_url:
  twitter_url: https://twitter.com/remax
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'California Real Estate Podcast with Kevin Peete'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the California Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from RE/MAX PATRIOTS - your professional California Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in California, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kevin Peete'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: California Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e11b22'
  theme_color: '#323232'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
